Add -a option
Running rdb with the '-a' option will execute commands on all connected devices

diff --git a/rdb b/rdb
--- a/rdb
+++ b/rdb
@@ -36,6 +36,9 @@ while [[ $# > 0 && $1 == -* ]] ; do
       export RDB_DEVICE_SELECT="-s ${!2:-$2}"
       shift
       ;;
+    -a )
+      RDB_EXECUTE_ON_ALL_DEVICES=true
+      ;;
     * )
       echo "$(tput setaf 1)Option '$1' not recognized.$(tput sgr0)"
       $(get_command_full_path "${RDB_COMMAND_HELP_NAME}")
@@ -57,6 +60,23 @@ else
     $(get_command_full_path "${RDB_COMMAND_HELP_NAME}")
     exit 1
   else
-    $RDB_COMMAND "$@"
+    if [ "${RDB_EXECUTE_ON_ALL_DEVICES}" == true ] ; then
+      if [[ "${RDB_COMMAND}" == "${RDB_COMMANDS_SYNCHRONOUS_PATH}"* ]] ; then
+        echo "$(tput setaf 1)Unable to execute command with multiple devices connected.$(tput sgr0)"
+        exit 1
+      fi
+      echo
+      while read -u 3 line ; do
+        if [ ! "$line" = "" ] && [ `echo $line | awk '{print $2}'` = "device" ] ; then
+          device=`echo $line | awk '{print $1}'`
+          echo "Executing on device: $(tput setaf 6)${device}$(tput sgr0) ["`echo $line | awk '{print $4}'`"]"
+          export RDB_DEVICE_SELECT="-s ${device}"
+          $RDB_COMMAND "$@"
+          echo
+        fi
+      done 3<<< "$(adb devices -l)"
+    else
+      $RDB_COMMAND "$@"
+    fi
   fi
 fi
